### id -> problem id, name -> problem title, tag -> "tag1 tag2 tag3"
POST http://localhost:8080/api/problem
content-type: application/json

{
  "start": 1,
  "end": 1,
  "filter": {
    "id": "",
    "name": "",
    "tag": ""
  }
}

### user -> username/ nickname problem -> problem title assignment -> assignment title
POST http://localhost:8080/api/record
content-type: application/json

{
  "start": 1,
  "end": 1,
  "filter": {
    "user": "",
    "problem": "",
    "assignment": ""
  }
}

### id -> assignment id, name -> assignment name
POST http://localhost:8080/api/assignment
content-type: application/json

{
  "start": 1,
  "end": 1,
  "filter": {
    "id": "",
    "name": ""
  }
}

###
POST http://localhost:8080/api/sendvcode/11813207@mail.sustech.edu.cn

<> 2020-11-22T163147.200.jstd
<> 2020-11-22T162249.200.jstd
<> 2020-11-22T162218.200.jstd
<> 2020-11-22T162207.200.jstd
<> 2020-11-22T160841.500.json

###
POST http://localhost:8080/api/signup
content-type: application/json

{
  "username": "11811620@mail.sustech.edu.cn",
  "password": "11811620",
  "vcode": "449432"
}

###
POST http://localhost:8080/api/login
content-type: application/json

{
  "username": "11811407@mail.sustech.edu.cn",
  "password": "11811407"
}


###
POST http://localhost:8080/api/problem/1/submit
content-type: application/json

{
"code": "SELECT title, country, year_released FROM movies WHERE country <>'us' AND year_released = 1991 AND title LIKE 'The%'",
  "dialect": "pgsql",
  "submitTime": 12345
}

###
###
GET http://localhost:8080/api/record/6