POST http://localhost:9999/api/user/signup
Content-Type: application/json

{
  "username": "11811410@mail.sustech.edu.cn",
  "password": "lsl213",
  "nickname": "god"
}

###

POST http://localhost:8080/api/problem
Content-Type: application/json

{
  "start": 1,
  "end": 10,
  "filter": {

  }
}