server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:postgresql://localhost:5432/testsec?useAffectedRows=true
      username: postgres
      password: abc123
      driver-class-name: org.postgresql.Driver
      initial-size: 8
      min-idle: 1
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;mergesql=false
      use-global-data-source-stat: true
#      filter:
#        log4j:
#          enabled: true
#          statement-create-after-log-enabled: false
#          statement-close-after-log-enabled: false
#          result-set-open-after-log-enabled: false
#          result-set-close-after-log-enabled: false


  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  mail:
    host: smtp.qq.com
    username: 695297502@qq.com
    password: cpbfgjargvrkbeec
    default-encoding: utf-8
    properties: { mail.smtp.auth: true,mail.smtp.port: 465,mail.smtp.ssl.enable: true }
    protocol: smtp
  redis:
    timeout: 5000
    database: 0
    host: 10.20.87.51
    port: 6379

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: sustech.edu.phantom.dboj.entity.*
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file-root-path:
  windows: C:\Users\
  linux: /resources/
  default-avatar-filename: phantom.svg
#logging:
#  config: classpath:log4j2.yml
